defmodule NASR.Entities.LocationIdentifier do
  @moduledoc "Entity struct for USA (LOCATION IDENTIFIERS) records"
  import NASR.Utils
  
  defstruct [
    :identifier_group_sort_code,
    :identifier_group_code,
    :location_identifier,
    :faa_region,
    :state,
    :city,
    :controlling_artcc,
    :controlling_artcc_computer_id,
    :facility_type,
    :facility_name,
    :navaid_facility_name_1,
    :navaid_facility_type_1,
    :navaid_facility_name_2,
    :navaid_facility_type_2,
    :navaid_facility_name_3,
    :navaid_facility_type_3,
    :navaid_facility_name_4,
    :navaid_facility_type_4,
    :ils_runway_end,
    :ils_facility_type,
    :ils_airport_identifier,
    :ils_airport_name,
    :fss_identifier,
    :fss_name,
    :artcc_name,
    :artcc_facility_type,
    :flight_watch_indicator,
    :other_facility_name,
    :other_facility_type,
    :effective_date
  ]
  
  @type t() :: %__MODULE__{
    identifier_group_sort_code: String.t() | nil,
    identifier_group_code: String.t() | nil,
    location_identifier: String.t() | nil,
    faa_region: String.t() | nil,
    state: String.t() | nil,
    city: String.t() | nil,
    controlling_artcc: String.t() | nil,
    controlling_artcc_computer_id: String.t() | nil,
    facility_type: String.t() | nil,
    facility_name: String.t() | nil,
    navaid_facility_name_1: String.t() | nil,
    navaid_facility_type_1: String.t() | nil,
    navaid_facility_name_2: String.t() | nil,
    navaid_facility_type_2: String.t() | nil,
    navaid_facility_name_3: String.t() | nil,
    navaid_facility_type_3: String.t() | nil,
    navaid_facility_name_4: String.t() | nil,
    navaid_facility_type_4: String.t() | nil,
    ils_runway_end: String.t() | nil,
    ils_facility_type: String.t() | nil,
    ils_airport_identifier: String.t() | nil,
    ils_airport_name: String.t() | nil,
    fss_identifier: String.t() | nil,
    fss_name: String.t() | nil,
    artcc_name: String.t() | nil,
    artcc_facility_type: String.t() | nil,
    flight_watch_indicator: String.t() | nil,
    other_facility_name: String.t() | nil,
    other_facility_type: String.t() | nil,
    effective_date: Date.t() | nil
  }
  
  @spec new(map()) :: t()
  def new(entry) do
    %__MODULE__{
      identifier_group_sort_code: entry.identifier_group_sort_code,
      identifier_group_code: entry.identifier_group_code,
      location_identifier: entry.location_identifier,
      faa_region: entry.faa_region_associated_with_the_location_identifier,
      state: entry.state_associated_with_the_location_identifier,
      city: entry.city_associated_with_the_location_identifier,
      controlling_artcc: entry.controlling_artcc_for_this_location,
      controlling_artcc_computer_id: entry.controlling_artcc_for_this_location___computer_id,
      facility_type: entry.landing_facility_type,
      facility_name: entry.landing_facility_name,
      navaid_facility_name_1: entry.navaid_facility_name_1,
      navaid_facility_type_1: entry.navaid_facility_type_1,
      navaid_facility_name_2: entry.navaid_facility_name_2,
      navaid_facility_type_2: entry.navaid_facility_type_2,
      navaid_facility_name_3: entry.navaid_facility_name_3,
      navaid_facility_type_3: entry.navaid_facility_type_3,
      navaid_facility_name_4: entry.navaid_facility_name_4,
      navaid_facility_type_4: entry.navaid_facility_type_4,
      ils_runway_end: entry.ils_runway_end_ex_08_18r_36l,
      ils_facility_type: entry.ils_facility_type,
      ils_airport_identifier: entry.location_identifier_of_ils_airport,
      ils_airport_name: entry.ils_airport_name,
      fss_identifier: entry.tie_in_flight_service_station_fss_identifier,
      fss_name: entry.fss_name,
      artcc_name: entry.artcc_name,
      artcc_facility_type: entry.artcc_facility_type,
      flight_watch_indicator: entry.flight_watch_station_fltwo_indicator,
      other_facility_name: entry.other_facility___facility_name_description,
      other_facility_type: entry.other_facility___facility_type,
      effective_date: parse_date(entry.effective_date_of_this_information_mm_dd_yyyy)
    }
  end
end