defmodule NASR.Entities.NavigationAidBaseData do
  @moduledoc "Entity struct for NAV1 (BASE DATA) records"
  import NASR.Utils

  defstruct [
    :record_type_indicator,
    :navaid_facility_identifier,
    :navaid_facility_type,
    :official_navaid_facility_identifier,
    :effective_date,
    :navaid_name,
    :associated_city,
    :associated_state_name,
    :state_post_office_code,
    :faa_region_code,
    :country_name,
    :country_post_office_code,
    :navaid_owner_name,
    :navaid_operator_name,
    :common_system_usage,
    :navaid_public_use,
    :navaid_class,
    :hours_of_operation,
    :high_altitude_artcc_id,
    :high_altitude_artcc_name,
    :low_altitude_artcc_id,
    :low_altitude_artcc_name,
    :navaid_latitude_formatted,
    :navaid_latitude_seconds,
    :navaid_longitude_formatted,
    :navaid_longitude_seconds,
    :latitude_longitude_survey_accuracy,
    :tacan_latitude_formatted,
    :tacan_latitude_seconds,
    :tacan_longitude_formatted,
    :tacan_longitude_seconds,
    :elevation_tenth_foot_msl,
    :magnetic_variation_degrees,
    :magnetic_variation_epoch_year,
    :simultaneous_voice_feature,
    :power_output_watts,
    :automatic_voice_identification,
    :monitoring_category,
    :radio_voice_call,
    :tacan_channel,
    :frequency,
    :fan_marker_identifier,
    :fan_marker_type,
    :fan_marker_bearing,
    :vor_standard_service_volume,
    :dme_standard_service_volume,
    :low_altitude_facility_used_in_high_structure,
    :navaid_z_marker_available,
    :tweb_hours,
    :tweb_phone_number,
    :controlling_fss_id,
    :controlling_fss_name,
    :fss_hours_of_operation,
    :notam_accountability_code,
    :quadrant_identification,
    :navaid_status,
    :pitch_flag,
    :catch_flag,
    :sua_atcaa_flag,
    :navaid_restriction_flag,
    :hiwas_flag,
    :tweb_restriction
  ]

  @type t() :: %__MODULE__{
    record_type_indicator: String.t() | nil,
    navaid_facility_identifier: String.t() | nil,
    navaid_facility_type: String.t() | nil,
    official_navaid_facility_identifier: String.t() | nil,
    effective_date: Date.t() | nil,
    navaid_name: String.t() | nil,
    associated_city: String.t() | nil,
    associated_state_name: String.t() | nil,
    state_post_office_code: String.t() | nil,
    faa_region_code: String.t() | nil,
    country_name: String.t() | nil,
    country_post_office_code: String.t() | nil,
    navaid_owner_name: String.t() | nil,
    navaid_operator_name: String.t() | nil,
    common_system_usage: boolean() | nil,
    navaid_public_use: boolean() | nil,
    navaid_class: String.t() | nil,
    hours_of_operation: String.t() | nil,
    high_altitude_artcc_id: String.t() | nil,
    high_altitude_artcc_name: String.t() | nil,
    low_altitude_artcc_id: String.t() | nil,
    low_altitude_artcc_name: String.t() | nil,
    navaid_latitude_formatted: String.t() | nil,
    navaid_latitude_seconds: String.t() | nil,
    navaid_longitude_formatted: String.t() | nil,
    navaid_longitude_seconds: String.t() | nil,
    latitude_longitude_survey_accuracy: String.t() | nil,
    tacan_latitude_formatted: String.t() | nil,
    tacan_latitude_seconds: String.t() | nil,
    tacan_longitude_formatted: String.t() | nil,
    tacan_longitude_seconds: String.t() | nil,
    elevation_tenth_foot_msl: float() | nil,
    magnetic_variation_degrees: String.t() | nil,
    magnetic_variation_epoch_year: integer() | nil,
    simultaneous_voice_feature: boolean() | nil,
    power_output_watts: integer() | nil,
    automatic_voice_identification: boolean() | nil,
    monitoring_category: integer() | nil,
    radio_voice_call: String.t() | nil,
    tacan_channel: String.t() | nil,
    frequency: float() | nil,
    fan_marker_identifier: String.t() | nil,
    fan_marker_type: String.t() | nil,
    fan_marker_bearing: String.t() | nil,
    vor_standard_service_volume: String.t() | nil,
    dme_standard_service_volume: String.t() | nil,
    low_altitude_facility_used_in_high_structure: boolean() | nil,
    navaid_z_marker_available: boolean() | nil,
    tweb_hours: String.t() | nil,
    tweb_phone_number: String.t() | nil,
    controlling_fss_id: String.t() | nil,
    controlling_fss_name: String.t() | nil,
    fss_hours_of_operation: String.t() | nil,
    notam_accountability_code: String.t() | nil,
    quadrant_identification: String.t() | nil,
    navaid_status: String.t() | nil,
    pitch_flag: boolean() | nil,
    catch_flag: boolean() | nil,
    sua_atcaa_flag: boolean() | nil,
    navaid_restriction_flag: boolean() | nil,
    hiwas_flag: boolean() | nil,
    tweb_restriction: boolean() | nil
  }

  @spec new(map()) :: t()
  def new(entry) do
    %__MODULE__{
      record_type_indicator: entry.record_type_indicator,
      navaid_facility_identifier: entry.navaid_facility_identifier,
      navaid_facility_type: entry.navaid_facility_type_see_description,
      official_navaid_facility_identifier: entry.official_navaid_facility_identifier,
      effective_date: parse_date(entry.effective_date_this_date_coincides_with),
      navaid_name: entry.name_of_navaid_ex_washington,
      associated_city: entry.city_associated_with_the_navaid_ex_washington,
      associated_state_name: entry.state_name_where_associated_city_is_located,
      state_post_office_code: entry.state_post_office_code_where_associated_city_is,
      faa_region_code: entry.faa_region_responsible_for_navaid_code_ex_aea,
      country_name: entry.country_navaid_located_if_other_than_u_s_name,
      country_post_office_code: entry.country_post_office_code_navaid_located_if,
      navaid_owner_name: entry.navaid_owner_name_ex_u_s_navy,
      navaid_operator_name: entry.navaid_operator_name_ex_u_s_navy,
      common_system_usage: convert_yn(entry.common_system_usage_y_or_n_defines_how_the),
      navaid_public_use: convert_yn(entry.navaid_public_use_y_or_n_defines_by_whom),
      navaid_class: entry.class_of_navaid_the_navaid_class_designator,
      hours_of_operation: entry.hours_of_operation_of_navaid_ex_0800_2400,
      high_altitude_artcc_id: entry.identifier_of_artcc_with_high_altitude_boundary,
      high_altitude_artcc_name: entry.name_of_artcc_with_high_altitude_boundary_that,
      low_altitude_artcc_id: entry.identifier_of_artcc_with_low_altitude_boundary,
      low_altitude_artcc_name: entry.name_of_artcc_with_low_altitude_boundary_that,
      navaid_latitude_formatted: entry.navaid_latitude_formatted,
      navaid_latitude_seconds: entry.navaid_latitude_all_seconds,
      navaid_longitude_formatted: entry.navaid_longitude_formatted,
      navaid_longitude_seconds: entry.navaid_longitude_all_seconds,
      latitude_longitude_survey_accuracy: entry.latitude_longitude_survery_accuracy_code,
      tacan_latitude_formatted: entry.latitude_of_tacan_portion_of_vortac_when_tacan,
      tacan_latitude_seconds: entry.latitude_of_tacan_portion_of_vortac_when_tacan_0,
      tacan_longitude_formatted: entry.longitude_of_tacan_portion_of_vortac_when_tacan,
      tacan_longitude_seconds: entry.longitude_of_tacan_portion_of_vortac_when_tacan_0,
      elevation_tenth_foot_msl: safe_str_to_float(entry.elevation_in_tenth_of_a_foot_msl),
      magnetic_variation_degrees: entry.magnetic_variation_degrees_00_99_followed_by,
      magnetic_variation_epoch_year: safe_str_to_int(entry.magnetic_variation_epoch_year_ex_2015),
      simultaneous_voice_feature: convert_yn(entry.simultaneous_voice_feature_y_n_or_null),
      power_output_watts: safe_str_to_int(entry.power_output_in_watts),
      automatic_voice_identification: convert_yn(entry.automatic_voice_identification_feature_y_n_or),
      monitoring_category: safe_str_to_int(entry.monitoring_category),
      radio_voice_call: entry.radio_voice_call_name_ex_washington_radio,
      tacan_channel: entry.channel_tacan_navaid_transmits_on_ex_51x,
      frequency: safe_str_to_float(entry.frequency_the_navaid_transmits_on_except_tacan),
      fan_marker_identifier: entry.transmitted_fan_marker_marine_radio_beacon,
      fan_marker_type: entry.fan_marker_type_bone_or_elliptical,
      fan_marker_bearing: entry.true_bearing_of_major_axis_of_fan_marker_ex,
      vor_standard_service_volume: entry.vor_standard_service_volume_h_high_altitude,
      dme_standard_service_volume: entry.dme_standard_service_volume_h_high_altitude,
      low_altitude_facility_used_in_high_structure: convert_yn(entry.low_altitude_facility_used_in_high_structure),
      navaid_z_marker_available: convert_yn(entry.navaid_z_marker_available_y_n_or_null),
      tweb_hours: entry.transcribed_weather_broadcast_hours_tweb_ex,
      tweb_phone_number: entry.transcribed_weather_broadcast_phone_number,
      controlling_fss_id: entry.associated_controlling_fss_ident,
      controlling_fss_name: entry.associated_controlling_fss_name,
      fss_hours_of_operation: entry.hours_of_operation_of_controlling_fss_ex_0800,
      notam_accountability_code: entry.notam_accountability_code_ident,
      quadrant_identification: entry.quadrant_identification_and_range_leg_bearing,
      navaid_status: entry.navigation_aid_status,
      pitch_flag: convert_yn(entry.pitch_flag_y_or_n),
      catch_flag: convert_yn(entry.catch_flag_y_or_n),
      sua_atcaa_flag: convert_yn(entry.sua_atcaa_flag_y_or_n),
      navaid_restriction_flag: convert_yn(entry.navaid_restriction_flag_y_n_or_null),
      hiwas_flag: convert_yn(entry.hiwas_flag_y_n_or_null),
      tweb_restriction: convert_yn(entry.transcribed_weather_broadcast_tweb_restriction)
    }
  end
end